Import from Big Query:

In [2]:
from pandas.io import gbq
df = gbq.read_gbq('SELECT * FROM btc.krakenUSD', project_id='predcoin')

Requesting query... ok.
Job ID: job_y_dl3KDFnne4c2A5-QY7YxSPiUAi
Query running...
  Elapsed 11.35 s. Waiting...
Query done.
Processed: 104.2 MB
Standard price: $0.00 USD

Retrieving results...
  Got page: 1; 3% done. Elapsed 21.35 s.
  Got page: 2; 5% done. Elapsed 27.26 s.
  Got page: 3; 8% done. Elapsed 32.66 s.
  Got page: 4; 10% done. Elapsed 37.83 s.
  Got page: 5; 13% done. Elapsed 43.03 s.
  Got page: 6; 15% done. Elapsed 49.87 s.
  Got page: 7; 18% done. Elapsed 56.45 s.
  Got page: 8; 21% done. Elapsed 62.25 s.
  Got page: 9; 23% done. Elapsed 68.14 s.
  Got page: 10; 26% done. Elapsed 83.33 s.
  Got page: 11; 28% done. Elapsed 88.13 s.
  Got page: 12; 31% done. Elapsed 93.74 s.
  Got page: 13; 33% done. Elapsed 108.92 s.
  Got page: 14; 36% done. Elapsed 121.25 s.
  Got page: 15; 38% done. Elapsed 126.46 s.
  Got page: 16; 41% done. Elapsed 138.69 s.
  Got page: 17; 44% done. Elapsed 151.82 s.
  Got page: 18; 46% done. Elapsed 163.33 s.
  Got page: 19; 49% done. Elapsed 168.73 s.
  Got page: 20; 51% done. Elapsed 182.58 s.
  Got page: 21; 54% done. Elapsed 188.55 s.
  Got page: 22; 56% done. Elapsed 193.9 s.
  Got page: 23; 59% done. Elapsed 198.97 s.
  Got page: 24; 62% done. Elapsed 212.11 s.
  Got page: 25; 64% done. Elapsed 217.97 s.
  Got page: 26; 67% done. Elapsed 222.24 s.
  Got page: 27; 69% done. Elapsed 226.17 s.
  Got page: 28; 72% done. Elapsed 230.65 s.
  Got page: 29; 74% done. Elapsed 235.66 s.
  Got page: 30; 77% done. Elapsed 249.51 s.
  Got page: 31; 79% done. Elapsed 255.24 s.
  Got page: 32; 82% done. Elapsed 261.2 s.
  Got page: 33; 85% done. Elapsed 265.59 s.
  Got page: 34; 87% done. Elapsed 271.41 s.
  Got page: 35; 90% done. Elapsed 276.72 s.
  Got page: 36; 92% done. Elapsed 283.64 s.
  Got page: 37; 95% done. Elapsed 288.45 s.
  Got page: 38; 97% done. Elapsed 298.38 s.
  Got page: 39; 100% done. Elapsed 304.61 s.
  Got page: 40; 100% done. Elapsed 305.55 s.
Got 1706404 rows.

Total time taken 330.75 s.
Finished at 2017-09-14 19:28:34.

In [3]:
df

,Timestamp,Open,High,Low,Close,Volume_BTC,Volume_USD,Volume_Weighted_Price
0,1492737660,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1492738080,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1492739580,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1492741320,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1492742340,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1492743780,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1492757340,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1492802280,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1492814940,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1492818300,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,1492818360,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,1492822680,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,1492826340,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,1492826520,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,1492832100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,1492835940,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,1492846140,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,1492853940,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,1492879560,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,1492886220,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,1492897860,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,1492906860,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,1492914540,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,1492935960,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,1492938300,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,1492950480,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,1492954260,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,1492958520,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,1492963740,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,1492966980,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
1706374,1482943980,951.291,951.291,951.291,951.291,0.000158,0.149914,951.291000
1706375,1482945600,955.999,956.000,955.999,956.000,1.569038,1499.999999,955.999668
1706376,1482945720,956.000,956.000,956.000,956.000,3.000000,2868.000000,956.000000
1706377,1482953940,970.800,970.800,966.041,968.001,4.117360,3989.982700,969.063356
1706378,1482959100,974.000,974.000,973.998,974.000,47.754315,46512.699826,973.999937
1706379,1482960540,966.533,966.533,961.046,961.046,3.657454,3527.639860,964.506871
1706380,1482961140,966.997,966.997,966.997,966.997,0.192000,185.663424,966.997000
1706381,1482963120,974.231,974.231,974.231,974.231,0.037690,36.718766,974.231000
1706382,1482977880,976.610,976.610,976.610,976.610,0.000450,0.439474,976.610000
1706383,1482981360,976.010,976.010,976.010,976.010,1.300000,1268.813000,976.010000
1706384,1482984300,973.810,973.810,973.810,973.810,0.010000,9.738100,973.810000
1706385,1482985260,971.668,971.668,971.630,971.630,0.223221,216.896293,971.666298
1706386,1482986100,974.359,974.359,972.380,972.380,0.020000,19.467390,973.369500
1706387,1482986340,972.000,972.000,972.000,972.000,0.084000,81.648000,972.000000
1706388,1482990000,975.892,975.892,975.892,975.892,0.200000,195.178400,975.892000
1706389,1482995520,977.250,977.250,977.130,977.130,3.627000,3544.056510,977.131654
1706390,1483017780,981.499,981.499,981.499,981.499,0.601600,590.469798,981.499000
1706391,1483020180,967.153,967.153,967.131,967.131,5.000000,4835.754796,967.150959
1706392,1483026720,969.468,969.468,969.468,969.468,0.008394,8.138122,969.468000
1706393,1483028040,971.000,971.000,971.000,971.000,1.000000,971.000000,971.000000
1706394,1483039380,960.280,960.280,960.250,960.250,4.214824,4047.399886,960.277318
1706395,1483039620,960.250,960.250,960.250,960.250,1.001120,961.325480,960.250000
1706396,1483065360,967.021,967.021,967.000,967.000,0.698888,675.832780,967.011636
1706397,1483081560,950.560,950.560,950.490,950.490,1.642560,1561.340860,950.553319
1706398,1483086600,945.440,945.440,943.190,943.190,0.339090,319.936750,943.515732
1706399,1483093080,931.470,931.470,931.470,931.470,0.069562,64.794953,931.470000
1706400,1483093560,936.480,939.891,934.001,936.460,6.756856,6334.763482,937.531183
1706401,1483095420,940.377,940.377,939.920,939.920,1.756584,1651.534888,940.196815
1706402,1483105020,954.230,954.240,954.230,954.230,1.701248,1623.387236,954.233036
1706403,1483105140,954.230,954.230,954.230,954.230,2.203589,2102.731066,954.230000

In [6]:
df["Volume_Weighted_Price"]

0                 NaN
1                 NaN
2                 NaN
3                 NaN
4                 NaN
5                 NaN
6                 NaN
7                 NaN
8                 NaN
9                 NaN
10                NaN
11                NaN
12                NaN
13                NaN
14                NaN
15                NaN
16                NaN
17                NaN
18                NaN
19                NaN
20                NaN
21                NaN
22                NaN
23                NaN
24                NaN
25                NaN
26                NaN
27                NaN
28                NaN
29                NaN
              ...
1706374    951.291000
1706375    955.999668
1706376    956.000000
1706377    969.063356
1706378    973.999937
1706379    964.506871
1706380    966.997000
1706381    974.231000
1706382    976.610000
1706383    976.010000
1706384    973.810000
1706385    971.666298
1706386    973.369500
1706387    972.000000
1706388    975.892000
1706389    977.131654
1706390    981.499000
1706391    967.150959
1706392    969.468000
1706393    971.000000
1706394    960.277318
1706395    960.250000
1706396    967.011636
1706397    950.553319
1706398    943.515732
1706399    931.470000
1706400    937.531183
1706401    940.196815
1706402    954.233036
1706403    954.230000
Name: Volume_Weighted_Price, Length: 1706404, dtype: float64

In [16]:
def clean(df, rows):
    df_norm = df.fillna(0)
    df_norm = (df - df.mean()) / (df.max() - df.min())
    df_sample = df[:-rows]
    return(df_sample)

df_small_cleaned = clean(df, 500)
df_small_cleaned.describe()

,Timestamp,Open,High,Low,Close,Volume_BTC,Volume_USD,Volume_Weighted_Price
count,1.705904e+06,1.705904e+06,1.705904e+06,1.705904e+06,1.705904e+06,1.705904e+06,1.705904e+06,1.705904e+06
mean,1.442644e+09,1.575038e+02,1.576174e+02,1.573903e+02,1.575017e+02,5.914850e-01,6.054251e+02,1.575025e+02
std,3.130211e+07,3.993918e+02,3.997624e+02,3.990315e+02,3.993886e+02,4.089430e+00,4.510933e+03,3.993887e+02
min,1.389119e+09,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.415918e+09,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,1.441644e+09,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,1.470570e+09,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
max,1.496189e+09,2.713371e+03,2.722237e+03,2.713365e+03,2.713368e+03,6.615264e+02,1.141599e+06,2.719497e+03

In [17]:
import numpy as np 

def load_data(dataset, seq_len):
    data = dataset
    
    sequence_length = seq_len + 1
    result = []
    for index in range(len(data) - sequence_length):
        result.append(data[index: index + sequence_length])

    result = np.array(result)

    row = round(0.9 * result.shape[0])
    
    train = result[:int(row), :]
    np.random.shuffle(train)
    x_train = train[:, :-1]
    y_train = train[:, -1]
    x_test = result[int(row):, :-1]
    y_test = result[int(row):, -1]

    x_train = np.reshape(x_train, (x_train.shape[0], x_train.shape[1], 1))
    x_test = np.reshape(x_test, (x_test.shape[0], x_test.shape[1], 1))  

    return [x_train, y_train, x_test, y_test]

[array([[[ 0.],
         [ 0.],
         [ 0.],
         ...,
         [ 0.],
         [ 0.],
         [ 0.]],

        [[ 0.],
         [ 0.],
         [ 0.],
         ...,
         [ 0.],
         [ 0.],
         [ 0.]],

        [[ 0.],
         [ 0.],
         [ 0.],
         ...,
         [ 0.],
         [ 0.],
         [ 0.]],

        ...,
        [[ 0.],
         [ 0.],
         [ 0.],
         ...,
         [ 0.],
         [ 0.],
         [ 0.]],

        [[ 0.],
         [ 0.],
         [ 0.],
         ...,
         [ 0.],
         [ 0.],
         [ 0.]],

        [[ 0.],
         [ 0.],
         [ 0.],
         ...,
         [ 0.],
         [ 0.],
         [ 0.]]]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([[[ 444.051     ],
         [ 443.49629659],
         [ 444.75      ],
         ...,
         [ 531.79898778],
         [ 529.42960155],
         [ 531.532     ]],

        [[ 443.49629659],
         [ 444.75      ],
         [ 445.94      ],
         ...,
         [ 529.42960155],
         [ 531.532     ],
         [ 531.89010634]],

        [[ 444.75      ],
         [ 445.94      ],
         [ 446.487     ],
         ...,
         [ 531.532     ],
         [ 531.89010634],
         [ 536.616     ]],

        ...,
        [[ 710.11      ],
         [ 723.77884998],
         [ 732.61353597],
         ...,
         [ 712.1       ],
         [ 712.        ],
         [ 716.        ]],

        [[ 723.77884998],
         [ 732.61353597],
         [ 731.06997229],
         ...,
         [ 712.        ],
         [ 716.        ],
         [ 716.5       ]],

        [[ 732.61353597],
         [ 731.06997229],
         [ 736.2505355 ],
         ...,
         [ 716.        ],
         [ 716.5       ],
         [ 716.5       ]]]),
 array([ 531.89010634,  536.616     ,  539.85      , ...,  716.5       ,
         716.5       ,  715.55      ])]

In [18]:
X_train, y_train, X_test, y_test = load_data(df_small_cleaned["Volume_Weighted_Price"], 60)

In [27]:
from keras.layers.core import Dense, Activation, Dropout
from keras.layers.recurrent import LSTM
from keras.models import Sequential
import time

def build_model(layers):
    model = Sequential()

    model.add(LSTM(
        input_dim=layers[0],
        output_dim=layers[1],
        return_sequences=True))
    model.add(Dropout(0.2))

    model.add(LSTM(
        layers[2],
        return_sequences=False))
    model.add(Dropout(0.2))

    model.add(Dense(
        output_dim=layers[3]))
    model.add(Activation("linear"))

    start = time.time()
    model.compile(loss="mse", optimizer="rmsprop")
    print("Compilation Time : ", time.time() - start)
    model.summary()
    return(model)

In [29]:
predmodel = build_model([1, 50, 100, 1])
predmodel.compile(loss='mse', optimizer='rmsprop')
predmodel.summary()

/Users/v/.anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:12: UserWarning: The `input_dim` and `input_length` arguments in recurrent layers are deprecated. Use `input_shape` instead.
  if sys.path[0] == '':
/Users/v/.anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:12: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(return_sequences=True, input_shape=(None, 1), units=50)`
  if sys.path[0] == '':

Compilation Time :  0.027080059051513672
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
lstm_3 (LSTM)                (None, None, 50)          10400
_________________________________________________________________
dropout_3 (Dropout)          (None, None, 50)          0
_________________________________________________________________
lstm_4 (LSTM)                (None, 100)               60400
_________________________________________________________________
dropout_4 (Dropout)          (None, 100)               0
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 101
_________________________________________________________________
activation_2 (Activation)    (None, 1)                 0
=================================================================
Total params: 70,901
Trainable params: 70,901
Non-trainable params: 0
_________________________________________________________________
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
lstm_3 (LSTM)                (None, None, 50)          10400
_________________________________________________________________
dropout_3 (Dropout)          (None, None, 50)          0
_________________________________________________________________
lstm_4 (LSTM)                (None, 100)               60400
_________________________________________________________________
dropout_4 (Dropout)          (None, 100)               0
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 101
_________________________________________________________________
activation_2 (Activation)    (None, 1)                 0
=================================================================
Total params: 70,901
Trainable params: 70,901
Non-trainable params: 0
_________________________________________________________________

/Users/v/.anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:21: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=1)`

In [ ]:
#Step 3 Train the model
predmodel.fit(
    X_train,
    y_train,
    batch_size=512,
    nb_epoch=1,
    validation_split=0.05)

/Users/v/.anaconda/lib/python3.6/site-packages/keras/models.py:848: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '

Train on 1458496 samples, validate on 76763 samples
Epoch 1/1
 584192/1458496 [===========>..................] - ETA: 1775s - loss: 76834.1521

In [ ]:
def predict_point_by_point(model, data):
    #Predict each timestep given the last sequence of true data, in effect only predicting 1 step ahead each time
    predicted = model.predict(data)
    predicted = np.reshape(predicted, (predicted.size,))
    return predicted

def predict_sequence_full(model, data, window_size):
    #Shift the window by 1 new prediction each time, re-run predictions on new window
    curr_frame = data[0]
    predicted = []
    for i in xrange(len(data)):
        predicted.append(model.predict(curr_frame[newaxis,:,:])[0,0])
        curr_frame = curr_frame[1:]
        curr_frame = np.insert(curr_frame, [window_size-1], predicted[-1], axis=0)
    return predicted

def predict_sequences_multiple(model, data, window_size, prediction_len):
    #Predict sequence of 50 steps before shifting prediction run forward by 50 steps
    prediction_seqs = []
    for i in xrange(len(data)/prediction_len):
        curr_frame = data[i*prediction_len]
        predicted = []
        for j in xrange(prediction_len):
            predicted.append(model.predict(curr_frame[newaxis,:,:])[0,0])
            curr_frame = curr_frame[1:]
            curr_frame = np.insert(curr_frame, [window_size-1], predicted[-1], axis=0)
        prediction_seqs.append(predicted)
    return prediction_seqs

def plot_results_multiple(predicted_data, true_data, prediction_len):
    fig = plt.figure(facecolor='white')
    ax = fig.add_subplot(111)
    ax.plot(true_data, label='True Data')
    print 'yo'
    #Pad the list of predictions to shift it in the graph to it's correct start
    for i, data in enumerate(predicted_data):
        padding = [None for p in xrange(i * prediction_len)]
        plt.plot(padding + data, label='Prediction')
        plt.legend()
    plt.show()

In [ ]:
# Step 4 - Plot the predictions!
predictions = lstm.predict_sequences_multiple(model, X_test, 50, 50)

In [ ]:
plot_results_multiple(predictions, y_test, 50)